IF EXISTS(SELECT TOP 1 * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[Insert]') AND type IN ( 'P', 'PC' ))
BEGIN
	DROP PROCEDURE dbo.[Insert]
END
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE dbo.[Insert]
	@Name VARCHAR(250)
AS BEGIN
	SET NOCOUNT ON;

	SET @Name = LTRIM(RTRIM(@Name));

	IF(EXISTS(SELECT TOP 1 Id FROM [Table] WHERE UPPER(Name) = UPPER(@Name)))
	BEGIN
		RAISERROR('Error.', 16, 1);
	END
	ELSE BEGIN
		DECLARE @Inserted TABLE(Id INT);

		BEGIN TRY
			INSERT INTO [Table] (Name)
			OUTPUT INSERTED.Id INTO @Inserted
			VALUES (@Name);

			SELECT Id FROM @Inserted;
		END TRY
		BEGIN CATCH
			RAISERROR('Error.', 16, 1);
		END CATCH
	END
END
GO