IF EXISTS(SELECT TOP 1 * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID('[Select]') AND type IN ( 'P', 'PC' ))
BEGIN
	DROP PROCEDURE dbo.[Select]
END
GO

SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO

CREATE PROCEDURE dbo.[Select]
	@Id	INT
AS BEGIN
	SET NOCOUNT ON;

	SELECT * FROM [Table] (NOLOCK) WHERE Id = @Id;
END
GO